name: CI / Publish

on:
  push:
    branches: [main]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build --silent

      - name: Bump version & push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version patch -m "ci: bump version to %s"
          git push --follow-tags

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
